channels:
  - robostack-experimental
  - conda-forge
dependencies:
  # ---------------------------------------------------------------------------
  # ROS Base Env deps
  # ---------------------------------------------------------------------------
  - python=3.8
  - ros-galactic-desktop
  - ca-certificates
  - openssl
  - compilers
  - cmake
  - pkg-config
  - make
  - ninja
  - numba
  # for some reason, not installed in base python?
  - typing-extensions
  - pycuda
  - pip
  - pytorch
  #- torchvision
  #- torchaudio
  #- cudatoolkit=10.2
  - pip:
    - colcon-common-extensions
    # colcon shell support
    - colcon-argcomplete
    - colcon-bash
    - colcon-zsh
    - python-can==4.0.0
variables:
  # fix for WSL RVIZ2
  LIBGL_ALWAYS_INDIRECT:
